/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ACharSimplefactor extends PSimplefactor
{
    private TCharsym _charsym_;

    public ACharSimplefactor()
    {
        // Constructor
    }

    public ACharSimplefactor(
        @SuppressWarnings("hiding") TCharsym _charsym_)
    {
        // Constructor
        setCharsym(_charsym_);

    }

    @Override
    public Object clone()
    {
        return new ACharSimplefactor(
            cloneNode(this._charsym_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACharSimplefactor(this);
    }

    public TCharsym getCharsym()
    {
        return this._charsym_;
    }

    public void setCharsym(TCharsym node)
    {
        if(this._charsym_ != null)
        {
            this._charsym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._charsym_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._charsym_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._charsym_ == child)
        {
            this._charsym_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._charsym_ == oldChild)
        {
            setCharsym((TCharsym) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
