/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ACompProgram extends PProgram
{
    private PComp _comp_;
    private PProgram _program_;

    public ACompProgram()
    {
        // Constructor
    }

    public ACompProgram(
        @SuppressWarnings("hiding") PComp _comp_,
        @SuppressWarnings("hiding") PProgram _program_)
    {
        // Constructor
        setComp(_comp_);

        setProgram(_program_);

    }

    @Override
    public Object clone()
    {
        return new ACompProgram(
            cloneNode(this._comp_),
            cloneNode(this._program_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompProgram(this);
    }

    public PComp getComp()
    {
        return this._comp_;
    }

    public void setComp(PComp node)
    {
        if(this._comp_ != null)
        {
            this._comp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comp_ = node;
    }

    public PProgram getProgram()
    {
        return this._program_;
    }

    public void setProgram(PProgram node)
    {
        if(this._program_ != null)
        {
            this._program_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._program_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comp_)
            + toString(this._program_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comp_ == child)
        {
            this._comp_ = null;
            return;
        }

        if(this._program_ == child)
        {
            this._program_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comp_ == oldChild)
        {
            setComp((PComp) newChild);
            return;
        }

        if(this._program_ == oldChild)
        {
            setProgram((PProgram) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
