/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ACondRelcomp extends PRelcomp
{
    private PRelexpr _relexpr_;

    public ACondRelcomp()
    {
        // Constructor
    }

    public ACondRelcomp(
        @SuppressWarnings("hiding") PRelexpr _relexpr_)
    {
        // Constructor
        setRelexpr(_relexpr_);

    }

    @Override
    public Object clone()
    {
        return new ACondRelcomp(
            cloneNode(this._relexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondRelcomp(this);
    }

    public PRelexpr getRelexpr()
    {
        return this._relexpr_;
    }

    public void setRelexpr(PRelexpr node)
    {
        if(this._relexpr_ != null)
        {
            this._relexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relexpr_ == child)
        {
            this._relexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relexpr_ == oldChild)
        {
            setRelexpr((PRelexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
