/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class AEndProgram extends PProgram
{
    private TEndsym _endsym_;

    public AEndProgram()
    {
        // Constructor
    }

    public AEndProgram(
        @SuppressWarnings("hiding") TEndsym _endsym_)
    {
        // Constructor
        setEndsym(_endsym_);

    }

    @Override
    public Object clone()
    {
        return new AEndProgram(
            cloneNode(this._endsym_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEndProgram(this);
    }

    public TEndsym getEndsym()
    {
        return this._endsym_;
    }

    public void setEndsym(TEndsym node)
    {
        if(this._endsym_ != null)
        {
            this._endsym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endsym_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._endsym_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._endsym_ == child)
        {
            this._endsym_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._endsym_ == oldChild)
        {
            setEndsym((TEndsym) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
