/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class AFactorTerm extends PTerm
{
    private PFactorexpr _factorexpr_;

    public AFactorTerm()
    {
        // Constructor
    }

    public AFactorTerm(
        @SuppressWarnings("hiding") PFactorexpr _factorexpr_)
    {
        // Constructor
        setFactorexpr(_factorexpr_);

    }

    @Override
    public Object clone()
    {
        return new AFactorTerm(
            cloneNode(this._factorexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFactorTerm(this);
    }

    public PFactorexpr getFactorexpr()
    {
        return this._factorexpr_;
    }

    public void setFactorexpr(PFactorexpr node)
    {
        if(this._factorexpr_ != null)
        {
            this._factorexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factorexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factorexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factorexpr_ == child)
        {
            this._factorexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factorexpr_ == oldChild)
        {
            setFactorexpr((PFactorexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
