/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ALshiftMulop extends PMulop
{
    private TLshiftsym _lshiftsym_;

    public ALshiftMulop()
    {
        // Constructor
    }

    public ALshiftMulop(
        @SuppressWarnings("hiding") TLshiftsym _lshiftsym_)
    {
        // Constructor
        setLshiftsym(_lshiftsym_);

    }

    @Override
    public Object clone()
    {
        return new ALshiftMulop(
            cloneNode(this._lshiftsym_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALshiftMulop(this);
    }

    public TLshiftsym getLshiftsym()
    {
        return this._lshiftsym_;
    }

    public void setLshiftsym(TLshiftsym node)
    {
        if(this._lshiftsym_ != null)
        {
            this._lshiftsym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lshiftsym_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lshiftsym_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lshiftsym_ == child)
        {
            this._lshiftsym_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lshiftsym_ == oldChild)
        {
            setLshiftsym((TLshiftsym) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
