/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class AMultTerm extends PTerm
{
    private PTerm _term_;
    private PMulop _mulop_;
    private PFactorexpr _factorexpr_;

    public AMultTerm()
    {
        // Constructor
    }

    public AMultTerm(
        @SuppressWarnings("hiding") PTerm _term_,
        @SuppressWarnings("hiding") PMulop _mulop_,
        @SuppressWarnings("hiding") PFactorexpr _factorexpr_)
    {
        // Constructor
        setTerm(_term_);

        setMulop(_mulop_);

        setFactorexpr(_factorexpr_);

    }

    @Override
    public Object clone()
    {
        return new AMultTerm(
            cloneNode(this._term_),
            cloneNode(this._mulop_),
            cloneNode(this._factorexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultTerm(this);
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    public PMulop getMulop()
    {
        return this._mulop_;
    }

    public void setMulop(PMulop node)
    {
        if(this._mulop_ != null)
        {
            this._mulop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mulop_ = node;
    }

    public PFactorexpr getFactorexpr()
    {
        return this._factorexpr_;
    }

    public void setFactorexpr(PFactorexpr node)
    {
        if(this._factorexpr_ != null)
        {
            this._factorexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factorexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._term_)
            + toString(this._mulop_)
            + toString(this._factorexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        if(this._mulop_ == child)
        {
            this._mulop_ = null;
            return;
        }

        if(this._factorexpr_ == child)
        {
            this._factorexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        if(this._mulop_ == oldChild)
        {
            setMulop((PMulop) newChild);
            return;
        }

        if(this._factorexpr_ == oldChild)
        {
            setFactorexpr((PFactorexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
