/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ANegatetypeFactor extends PFactor
{
    private TMinussym _minussym_;
    private PFactor _factor_;

    public ANegatetypeFactor()
    {
        // Constructor
    }

    public ANegatetypeFactor(
        @SuppressWarnings("hiding") TMinussym _minussym_,
        @SuppressWarnings("hiding") PFactor _factor_)
    {
        // Constructor
        setMinussym(_minussym_);

        setFactor(_factor_);

    }

    @Override
    public Object clone()
    {
        return new ANegatetypeFactor(
            cloneNode(this._minussym_),
            cloneNode(this._factor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegatetypeFactor(this);
    }

    public TMinussym getMinussym()
    {
        return this._minussym_;
    }

    public void setMinussym(TMinussym node)
    {
        if(this._minussym_ != null)
        {
            this._minussym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minussym_ = node;
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minussym_)
            + toString(this._factor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minussym_ == child)
        {
            this._minussym_ = null;
            return;
        }

        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minussym_ == oldChild)
        {
            setMinussym((TMinussym) newChild);
            return;
        }

        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
