/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExpr extends PExpr
{
    private PSimplexpr _simplexpr_;

    public ASimpleExpr()
    {
        // Constructor
    }

    public ASimpleExpr(
        @SuppressWarnings("hiding") PSimplexpr _simplexpr_)
    {
        // Constructor
        setSimplexpr(_simplexpr_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExpr(
            cloneNode(this._simplexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExpr(this);
    }

    public PSimplexpr getSimplexpr()
    {
        return this._simplexpr_;
    }

    public void setSimplexpr(PSimplexpr node)
    {
        if(this._simplexpr_ != null)
        {
            this._simplexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simplexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simplexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simplexpr_ == child)
        {
            this._simplexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simplexpr_ == oldChild)
        {
            setSimplexpr((PSimplexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
