/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ASimplefacFactorexpr extends PFactorexpr
{
    private PSimplefactor _simplefactor_;

    public ASimplefacFactorexpr()
    {
        // Constructor
    }

    public ASimplefacFactorexpr(
        @SuppressWarnings("hiding") PSimplefactor _simplefactor_)
    {
        // Constructor
        setSimplefactor(_simplefactor_);

    }

    @Override
    public Object clone()
    {
        return new ASimplefacFactorexpr(
            cloneNode(this._simplefactor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplefacFactorexpr(this);
    }

    public PSimplefactor getSimplefactor()
    {
        return this._simplefactor_;
    }

    public void setSimplefactor(PSimplefactor node)
    {
        if(this._simplefactor_ != null)
        {
            this._simplefactor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simplefactor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simplefactor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simplefactor_ == child)
        {
            this._simplefactor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simplefactor_ == oldChild)
        {
            setSimplefactor((PSimplefactor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
