/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExpr extends PExpr
{
    private PSimpleexpr _simpleexpr_;

    public ASimpleExpr()
    {
        // Constructor
    }

    public ASimpleExpr(
        @SuppressWarnings("hiding") PSimpleexpr _simpleexpr_)
    {
        // Constructor
        setSimpleexpr(_simpleexpr_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExpr(
            cloneNode(this._simpleexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExpr(this);
    }

    public PSimpleexpr getSimpleexpr()
    {
        return this._simpleexpr_;
    }

    public void setSimpleexpr(PSimpleexpr node)
    {
        if(this._simpleexpr_ != null)
        {
            this._simpleexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleexpr_ == child)
        {
            this._simpleexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleexpr_ == oldChild)
        {
            setSimpleexpr((PSimpleexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
