/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class ASucccharMonadexpr extends PMonadexpr
{
    private TSuccsym _succsym_;
    private PSimplefactor _simplefactor_;

    public ASucccharMonadexpr()
    {
        // Constructor
    }

    public ASucccharMonadexpr(
        @SuppressWarnings("hiding") TSuccsym _succsym_,
        @SuppressWarnings("hiding") PSimplefactor _simplefactor_)
    {
        // Constructor
        setSuccsym(_succsym_);

        setSimplefactor(_simplefactor_);

    }

    @Override
    public Object clone()
    {
        return new ASucccharMonadexpr(
            cloneNode(this._succsym_),
            cloneNode(this._simplefactor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASucccharMonadexpr(this);
    }

    public TSuccsym getSuccsym()
    {
        return this._succsym_;
    }

    public void setSuccsym(TSuccsym node)
    {
        if(this._succsym_ != null)
        {
            this._succsym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._succsym_ = node;
    }

    public PSimplefactor getSimplefactor()
    {
        return this._simplefactor_;
    }

    public void setSimplefactor(PSimplefactor node)
    {
        if(this._simplefactor_ != null)
        {
            this._simplefactor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simplefactor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._succsym_)
            + toString(this._simplefactor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._succsym_ == child)
        {
            this._succsym_ = null;
            return;
        }

        if(this._simplefactor_ == child)
        {
            this._simplefactor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._succsym_ == oldChild)
        {
            setSuccsym((TSuccsym) newChild);
            return;
        }

        if(this._simplefactor_ == oldChild)
        {
            setSimplefactor((PSimplefactor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
