/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class TLshiftsym extends Token
{
    public TLshiftsym()
    {
        super.setText("<<");
    }

    public TLshiftsym(int line, int pos)
    {
        super.setText("<<");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLshiftsym(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLshiftsym(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLshiftsym text.");
    }
}
