/* This file was generated by SableCC (http://www.sablecc.org/). */

package rm.node;

import rm.analysis.*;

@SuppressWarnings("nls")
public final class TSuccsym extends Token
{
    public TSuccsym()
    {
        super.setText("SUCC");
    }

    public TSuccsym(int line, int pos)
    {
        super.setText("SUCC");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSuccsym(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSuccsym(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSuccsym text.");
    }
}
